// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DNSProto.proto

public final class DNSProtos {
  private DNSProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string domain = 1;</code>
     */
    boolean hasDomain();
    /**
     * <code>required string domain = 1;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>required string domain = 1;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>required string ip = 2;</code>
     */
    boolean hasIp();
    /**
     * <code>required string ip = 2;</code>
     */
    java.lang.String getIp();
    /**
     * <code>required string ip = 2;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    java.util.List<DNSProtos.Address.KnownAddress> 
        getKnownaddressList();
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    DNSProtos.Address.KnownAddress getKnownaddress(int index);
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    int getKnownaddressCount();
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    java.util.List<? extends DNSProtos.Address.KnownAddressOrBuilder> 
        getKnownaddressOrBuilderList();
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    DNSProtos.Address.KnownAddressOrBuilder getKnownaddressOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      domain_ = "";
      ip_ = "";
      knownaddress_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              domain_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ip_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                knownaddress_ = new java.util.ArrayList<DNSProtos.Address.KnownAddress>();
                mutable_bitField0_ |= 0x00000004;
              }
              knownaddress_.add(
                  input.readMessage(DNSProtos.Address.KnownAddress.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          knownaddress_ = java.util.Collections.unmodifiableList(knownaddress_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DNSProtos.internal_static_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DNSProtos.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DNSProtos.Address.class, DNSProtos.Address.Builder.class);
    }

    public interface KnownAddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Address.KnownAddress)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string dmn = 1;</code>
       */
      boolean hasDmn();
      /**
       * <code>optional string dmn = 1;</code>
       */
      java.lang.String getDmn();
      /**
       * <code>optional string dmn = 1;</code>
       */
      com.google.protobuf.ByteString
          getDmnBytes();

      /**
       * <code>optional string ips = 2;</code>
       */
      boolean hasIps();
      /**
       * <code>optional string ips = 2;</code>
       */
      java.lang.String getIps();
      /**
       * <code>optional string ips = 2;</code>
       */
      com.google.protobuf.ByteString
          getIpsBytes();
    }
    /**
     * Protobuf type {@code Address.KnownAddress}
     */
    public  static final class KnownAddress extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Address.KnownAddress)
        KnownAddressOrBuilder {
      // Use KnownAddress.newBuilder() to construct.
      private KnownAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private KnownAddress() {
        dmn_ = "";
        ips_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private KnownAddress(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                dmn_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                ips_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DNSProtos.internal_static_Address_KnownAddress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DNSProtos.internal_static_Address_KnownAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DNSProtos.Address.KnownAddress.class, DNSProtos.Address.KnownAddress.Builder.class);
      }

      private int bitField0_;
      public static final int DMN_FIELD_NUMBER = 1;
      private volatile java.lang.Object dmn_;
      /**
       * <code>optional string dmn = 1;</code>
       */
      public boolean hasDmn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string dmn = 1;</code>
       */
      public java.lang.String getDmn() {
        java.lang.Object ref = dmn_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dmn_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string dmn = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDmnBytes() {
        java.lang.Object ref = dmn_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dmn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IPS_FIELD_NUMBER = 2;
      private volatile java.lang.Object ips_;
      /**
       * <code>optional string ips = 2;</code>
       */
      public boolean hasIps() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string ips = 2;</code>
       */
      public java.lang.String getIps() {
        java.lang.Object ref = ips_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ips_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ips = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpsBytes() {
        java.lang.Object ref = ips_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ips_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dmn_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ips_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dmn_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ips_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof DNSProtos.Address.KnownAddress)) {
          return super.equals(obj);
        }
        DNSProtos.Address.KnownAddress other = (DNSProtos.Address.KnownAddress) obj;

        boolean result = true;
        result = result && (hasDmn() == other.hasDmn());
        if (hasDmn()) {
          result = result && getDmn()
              .equals(other.getDmn());
        }
        result = result && (hasIps() == other.hasIps());
        if (hasIps()) {
          result = result && getIps()
              .equals(other.getIps());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasDmn()) {
          hash = (37 * hash) + DMN_FIELD_NUMBER;
          hash = (53 * hash) + getDmn().hashCode();
        }
        if (hasIps()) {
          hash = (37 * hash) + IPS_FIELD_NUMBER;
          hash = (53 * hash) + getIps().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static DNSProtos.Address.KnownAddress parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static DNSProtos.Address.KnownAddress parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static DNSProtos.Address.KnownAddress parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DNSProtos.Address.KnownAddress parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(DNSProtos.Address.KnownAddress prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Address.KnownAddress}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Address.KnownAddress)
          DNSProtos.Address.KnownAddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return DNSProtos.internal_static_Address_KnownAddress_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return DNSProtos.internal_static_Address_KnownAddress_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DNSProtos.Address.KnownAddress.class, DNSProtos.Address.KnownAddress.Builder.class);
        }

        // Construct using DNSProtos.Address.KnownAddress.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          dmn_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          ips_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return DNSProtos.internal_static_Address_KnownAddress_descriptor;
        }

        public DNSProtos.Address.KnownAddress getDefaultInstanceForType() {
          return DNSProtos.Address.KnownAddress.getDefaultInstance();
        }

        public DNSProtos.Address.KnownAddress build() {
          DNSProtos.Address.KnownAddress result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public DNSProtos.Address.KnownAddress buildPartial() {
          DNSProtos.Address.KnownAddress result = new DNSProtos.Address.KnownAddress(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.dmn_ = dmn_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.ips_ = ips_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DNSProtos.Address.KnownAddress) {
            return mergeFrom((DNSProtos.Address.KnownAddress)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DNSProtos.Address.KnownAddress other) {
          if (other == DNSProtos.Address.KnownAddress.getDefaultInstance()) return this;
          if (other.hasDmn()) {
            bitField0_ |= 0x00000001;
            dmn_ = other.dmn_;
            onChanged();
          }
          if (other.hasIps()) {
            bitField0_ |= 0x00000002;
            ips_ = other.ips_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DNSProtos.Address.KnownAddress parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DNSProtos.Address.KnownAddress) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object dmn_ = "";
        /**
         * <code>optional string dmn = 1;</code>
         */
        public boolean hasDmn() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string dmn = 1;</code>
         */
        public java.lang.String getDmn() {
          java.lang.Object ref = dmn_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              dmn_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string dmn = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDmnBytes() {
          java.lang.Object ref = dmn_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            dmn_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string dmn = 1;</code>
         */
        public Builder setDmn(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          dmn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string dmn = 1;</code>
         */
        public Builder clearDmn() {
          bitField0_ = (bitField0_ & ~0x00000001);
          dmn_ = getDefaultInstance().getDmn();
          onChanged();
          return this;
        }
        /**
         * <code>optional string dmn = 1;</code>
         */
        public Builder setDmnBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          dmn_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object ips_ = "";
        /**
         * <code>optional string ips = 2;</code>
         */
        public boolean hasIps() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string ips = 2;</code>
         */
        public java.lang.String getIps() {
          java.lang.Object ref = ips_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ips_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string ips = 2;</code>
         */
        public com.google.protobuf.ByteString
            getIpsBytes() {
          java.lang.Object ref = ips_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ips_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ips = 2;</code>
         */
        public Builder setIps(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          ips_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ips = 2;</code>
         */
        public Builder clearIps() {
          bitField0_ = (bitField0_ & ~0x00000002);
          ips_ = getDefaultInstance().getIps();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ips = 2;</code>
         */
        public Builder setIpsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          ips_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Address.KnownAddress)
      }

      // @@protoc_insertion_point(class_scope:Address.KnownAddress)
      private static final DNSProtos.Address.KnownAddress DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new DNSProtos.Address.KnownAddress();
      }

      public static DNSProtos.Address.KnownAddress getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<KnownAddress>
          PARSER = new com.google.protobuf.AbstractParser<KnownAddress>() {
        public KnownAddress parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new KnownAddress(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<KnownAddress> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<KnownAddress> getParserForType() {
        return PARSER;
      }

      public DNSProtos.Address.KnownAddress getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DOMAIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object domain_;
    /**
     * <code>required string domain = 1;</code>
     */
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string domain = 1;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string domain = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object ip_;
    /**
     * <code>required string ip = 2;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KNOWNADDRESS_FIELD_NUMBER = 3;
    private java.util.List<DNSProtos.Address.KnownAddress> knownaddress_;
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    public java.util.List<DNSProtos.Address.KnownAddress> getKnownaddressList() {
      return knownaddress_;
    }
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    public java.util.List<? extends DNSProtos.Address.KnownAddressOrBuilder> 
        getKnownaddressOrBuilderList() {
      return knownaddress_;
    }
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    public int getKnownaddressCount() {
      return knownaddress_.size();
    }
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    public DNSProtos.Address.KnownAddress getKnownaddress(int index) {
      return knownaddress_.get(index);
    }
    /**
     * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
     */
    public DNSProtos.Address.KnownAddressOrBuilder getKnownaddressOrBuilder(
        int index) {
      return knownaddress_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDomain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domain_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ip_);
      }
      for (int i = 0; i < knownaddress_.size(); i++) {
        output.writeMessage(3, knownaddress_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, domain_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ip_);
      }
      for (int i = 0; i < knownaddress_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, knownaddress_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DNSProtos.Address)) {
        return super.equals(obj);
      }
      DNSProtos.Address other = (DNSProtos.Address) obj;

      boolean result = true;
      result = result && (hasDomain() == other.hasDomain());
      if (hasDomain()) {
        result = result && getDomain()
            .equals(other.getDomain());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && getKnownaddressList()
          .equals(other.getKnownaddressList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasDomain()) {
        hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getDomain().hashCode();
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (getKnownaddressCount() > 0) {
        hash = (37 * hash) + KNOWNADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getKnownaddressList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DNSProtos.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DNSProtos.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DNSProtos.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DNSProtos.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DNSProtos.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DNSProtos.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DNSProtos.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DNSProtos.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DNSProtos.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DNSProtos.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DNSProtos.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        DNSProtos.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DNSProtos.internal_static_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DNSProtos.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DNSProtos.Address.class, DNSProtos.Address.Builder.class);
      }

      // Construct using DNSProtos.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getKnownaddressFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        domain_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (knownaddressBuilder_ == null) {
          knownaddress_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          knownaddressBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DNSProtos.internal_static_Address_descriptor;
      }

      public DNSProtos.Address getDefaultInstanceForType() {
        return DNSProtos.Address.getDefaultInstance();
      }

      public DNSProtos.Address build() {
        DNSProtos.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DNSProtos.Address buildPartial() {
        DNSProtos.Address result = new DNSProtos.Address(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.domain_ = domain_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        if (knownaddressBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            knownaddress_ = java.util.Collections.unmodifiableList(knownaddress_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.knownaddress_ = knownaddress_;
        } else {
          result.knownaddress_ = knownaddressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DNSProtos.Address) {
          return mergeFrom((DNSProtos.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DNSProtos.Address other) {
        if (other == DNSProtos.Address.getDefaultInstance()) return this;
        if (other.hasDomain()) {
          bitField0_ |= 0x00000001;
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000002;
          ip_ = other.ip_;
          onChanged();
        }
        if (knownaddressBuilder_ == null) {
          if (!other.knownaddress_.isEmpty()) {
            if (knownaddress_.isEmpty()) {
              knownaddress_ = other.knownaddress_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureKnownaddressIsMutable();
              knownaddress_.addAll(other.knownaddress_);
            }
            onChanged();
          }
        } else {
          if (!other.knownaddress_.isEmpty()) {
            if (knownaddressBuilder_.isEmpty()) {
              knownaddressBuilder_.dispose();
              knownaddressBuilder_ = null;
              knownaddress_ = other.knownaddress_;
              bitField0_ = (bitField0_ & ~0x00000004);
              knownaddressBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getKnownaddressFieldBuilder() : null;
            } else {
              knownaddressBuilder_.addAllMessages(other.knownaddress_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDomain()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DNSProtos.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DNSProtos.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object domain_ = "";
      /**
       * <code>required string domain = 1;</code>
       */
      public boolean hasDomain() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string domain = 1;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            domain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string domain = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string domain = 1;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string domain = 1;</code>
       */
      public Builder clearDomain() {
        bitField0_ = (bitField0_ & ~0x00000001);
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>required string domain = 1;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        domain_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>required string ip = 2;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip = 2;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        onChanged();
        return this;
      }

      private java.util.List<DNSProtos.Address.KnownAddress> knownaddress_ =
        java.util.Collections.emptyList();
      private void ensureKnownaddressIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          knownaddress_ = new java.util.ArrayList<DNSProtos.Address.KnownAddress>(knownaddress_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DNSProtos.Address.KnownAddress, DNSProtos.Address.KnownAddress.Builder, DNSProtos.Address.KnownAddressOrBuilder> knownaddressBuilder_;

      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public java.util.List<DNSProtos.Address.KnownAddress> getKnownaddressList() {
        if (knownaddressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(knownaddress_);
        } else {
          return knownaddressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public int getKnownaddressCount() {
        if (knownaddressBuilder_ == null) {
          return knownaddress_.size();
        } else {
          return knownaddressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public DNSProtos.Address.KnownAddress getKnownaddress(int index) {
        if (knownaddressBuilder_ == null) {
          return knownaddress_.get(index);
        } else {
          return knownaddressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder setKnownaddress(
          int index, DNSProtos.Address.KnownAddress value) {
        if (knownaddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownaddressIsMutable();
          knownaddress_.set(index, value);
          onChanged();
        } else {
          knownaddressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder setKnownaddress(
          int index, DNSProtos.Address.KnownAddress.Builder builderForValue) {
        if (knownaddressBuilder_ == null) {
          ensureKnownaddressIsMutable();
          knownaddress_.set(index, builderForValue.build());
          onChanged();
        } else {
          knownaddressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder addKnownaddress(DNSProtos.Address.KnownAddress value) {
        if (knownaddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownaddressIsMutable();
          knownaddress_.add(value);
          onChanged();
        } else {
          knownaddressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder addKnownaddress(
          int index, DNSProtos.Address.KnownAddress value) {
        if (knownaddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureKnownaddressIsMutable();
          knownaddress_.add(index, value);
          onChanged();
        } else {
          knownaddressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder addKnownaddress(
          DNSProtos.Address.KnownAddress.Builder builderForValue) {
        if (knownaddressBuilder_ == null) {
          ensureKnownaddressIsMutable();
          knownaddress_.add(builderForValue.build());
          onChanged();
        } else {
          knownaddressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder addKnownaddress(
          int index, DNSProtos.Address.KnownAddress.Builder builderForValue) {
        if (knownaddressBuilder_ == null) {
          ensureKnownaddressIsMutable();
          knownaddress_.add(index, builderForValue.build());
          onChanged();
        } else {
          knownaddressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder addAllKnownaddress(
          java.lang.Iterable<? extends DNSProtos.Address.KnownAddress> values) {
        if (knownaddressBuilder_ == null) {
          ensureKnownaddressIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, knownaddress_);
          onChanged();
        } else {
          knownaddressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder clearKnownaddress() {
        if (knownaddressBuilder_ == null) {
          knownaddress_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          knownaddressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public Builder removeKnownaddress(int index) {
        if (knownaddressBuilder_ == null) {
          ensureKnownaddressIsMutable();
          knownaddress_.remove(index);
          onChanged();
        } else {
          knownaddressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public DNSProtos.Address.KnownAddress.Builder getKnownaddressBuilder(
          int index) {
        return getKnownaddressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public DNSProtos.Address.KnownAddressOrBuilder getKnownaddressOrBuilder(
          int index) {
        if (knownaddressBuilder_ == null) {
          return knownaddress_.get(index);  } else {
          return knownaddressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public java.util.List<? extends DNSProtos.Address.KnownAddressOrBuilder> 
           getKnownaddressOrBuilderList() {
        if (knownaddressBuilder_ != null) {
          return knownaddressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(knownaddress_);
        }
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public DNSProtos.Address.KnownAddress.Builder addKnownaddressBuilder() {
        return getKnownaddressFieldBuilder().addBuilder(
            DNSProtos.Address.KnownAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public DNSProtos.Address.KnownAddress.Builder addKnownaddressBuilder(
          int index) {
        return getKnownaddressFieldBuilder().addBuilder(
            index, DNSProtos.Address.KnownAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .Address.KnownAddress knownaddress = 3;</code>
       */
      public java.util.List<DNSProtos.Address.KnownAddress.Builder> 
           getKnownaddressBuilderList() {
        return getKnownaddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DNSProtos.Address.KnownAddress, DNSProtos.Address.KnownAddress.Builder, DNSProtos.Address.KnownAddressOrBuilder> 
          getKnownaddressFieldBuilder() {
        if (knownaddressBuilder_ == null) {
          knownaddressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DNSProtos.Address.KnownAddress, DNSProtos.Address.KnownAddress.Builder, DNSProtos.Address.KnownAddressOrBuilder>(
                  knownaddress_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          knownaddress_ = null;
        }
        return knownaddressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final DNSProtos.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DNSProtos.Address();
    }

    public static DNSProtos.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public DNSProtos.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Address address = 1;</code>
     */
    java.util.List<DNSProtos.Address> 
        getAddressList();
    /**
     * <code>repeated .Address address = 1;</code>
     */
    DNSProtos.Address getAddress(int index);
    /**
     * <code>repeated .Address address = 1;</code>
     */
    int getAddressCount();
    /**
     * <code>repeated .Address address = 1;</code>
     */
    java.util.List<? extends DNSProtos.AddressOrBuilder> 
        getAddressOrBuilderList();
    /**
     * <code>repeated .Address address = 1;</code>
     */
    DNSProtos.AddressOrBuilder getAddressOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AddressList}
   */
  public  static final class AddressList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddressList)
      AddressListOrBuilder {
    // Use AddressList.newBuilder() to construct.
    private AddressList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressList() {
      address_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddressList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                address_ = new java.util.ArrayList<DNSProtos.Address>();
                mutable_bitField0_ |= 0x00000001;
              }
              address_.add(
                  input.readMessage(DNSProtos.Address.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          address_ = java.util.Collections.unmodifiableList(address_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DNSProtos.internal_static_AddressList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DNSProtos.internal_static_AddressList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DNSProtos.AddressList.class, DNSProtos.AddressList.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private java.util.List<DNSProtos.Address> address_;
    /**
     * <code>repeated .Address address = 1;</code>
     */
    public java.util.List<DNSProtos.Address> getAddressList() {
      return address_;
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    public java.util.List<? extends DNSProtos.AddressOrBuilder> 
        getAddressOrBuilderList() {
      return address_;
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    public DNSProtos.Address getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <code>repeated .Address address = 1;</code>
     */
    public DNSProtos.AddressOrBuilder getAddressOrBuilder(
        int index) {
      return address_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getAddressCount(); i++) {
        if (!getAddress(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < address_.size(); i++) {
        output.writeMessage(1, address_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < address_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, address_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DNSProtos.AddressList)) {
        return super.equals(obj);
      }
      DNSProtos.AddressList other = (DNSProtos.AddressList) obj;

      boolean result = true;
      result = result && getAddressList()
          .equals(other.getAddressList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DNSProtos.AddressList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DNSProtos.AddressList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DNSProtos.AddressList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DNSProtos.AddressList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DNSProtos.AddressList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DNSProtos.AddressList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DNSProtos.AddressList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DNSProtos.AddressList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DNSProtos.AddressList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DNSProtos.AddressList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DNSProtos.AddressList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressList)
        DNSProtos.AddressListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DNSProtos.internal_static_AddressList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DNSProtos.internal_static_AddressList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DNSProtos.AddressList.class, DNSProtos.AddressList.Builder.class);
      }

      // Construct using DNSProtos.AddressList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          addressBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DNSProtos.internal_static_AddressList_descriptor;
      }

      public DNSProtos.AddressList getDefaultInstanceForType() {
        return DNSProtos.AddressList.getDefaultInstance();
      }

      public DNSProtos.AddressList build() {
        DNSProtos.AddressList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DNSProtos.AddressList buildPartial() {
        DNSProtos.AddressList result = new DNSProtos.AddressList(this);
        int from_bitField0_ = bitField0_;
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            address_ = java.util.Collections.unmodifiableList(address_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DNSProtos.AddressList) {
          return mergeFrom((DNSProtos.AddressList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DNSProtos.AddressList other) {
        if (other == DNSProtos.AddressList.getDefaultInstance()) return this;
        if (addressBuilder_ == null) {
          if (!other.address_.isEmpty()) {
            if (address_.isEmpty()) {
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAddressIsMutable();
              address_.addAll(other.address_);
            }
            onChanged();
          }
        } else {
          if (!other.address_.isEmpty()) {
            if (addressBuilder_.isEmpty()) {
              addressBuilder_.dispose();
              addressBuilder_ = null;
              address_ = other.address_;
              bitField0_ = (bitField0_ & ~0x00000001);
              addressBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddressFieldBuilder() : null;
            } else {
              addressBuilder_.addAllMessages(other.address_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAddressCount(); i++) {
          if (!getAddress(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DNSProtos.AddressList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DNSProtos.AddressList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DNSProtos.Address> address_ =
        java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          address_ = new java.util.ArrayList<DNSProtos.Address>(address_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DNSProtos.Address, DNSProtos.Address.Builder, DNSProtos.AddressOrBuilder> addressBuilder_;

      /**
       * <code>repeated .Address address = 1;</code>
       */
      public java.util.List<DNSProtos.Address> getAddressList() {
        if (addressBuilder_ == null) {
          return java.util.Collections.unmodifiableList(address_);
        } else {
          return addressBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public int getAddressCount() {
        if (addressBuilder_ == null) {
          return address_.size();
        } else {
          return addressBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public DNSProtos.Address getAddress(int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);
        } else {
          return addressBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder setAddress(
          int index, DNSProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.set(index, value);
          onChanged();
        } else {
          addressBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder setAddress(
          int index, DNSProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.set(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(DNSProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(value);
          onChanged();
        } else {
          addressBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(
          int index, DNSProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddressIsMutable();
          address_.add(index, value);
          onChanged();
        } else {
          addressBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(
          DNSProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAddress(
          int index, DNSProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.add(index, builderForValue.build());
          onChanged();
        } else {
          addressBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder addAllAddress(
          java.lang.Iterable<? extends DNSProtos.Address> values) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, address_);
          onChanged();
        } else {
          addressBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public Builder removeAddress(int index) {
        if (addressBuilder_ == null) {
          ensureAddressIsMutable();
          address_.remove(index);
          onChanged();
        } else {
          addressBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public DNSProtos.Address.Builder getAddressBuilder(
          int index) {
        return getAddressFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public DNSProtos.AddressOrBuilder getAddressOrBuilder(
          int index) {
        if (addressBuilder_ == null) {
          return address_.get(index);  } else {
          return addressBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public java.util.List<? extends DNSProtos.AddressOrBuilder> 
           getAddressOrBuilderList() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(address_);
        }
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public DNSProtos.Address.Builder addAddressBuilder() {
        return getAddressFieldBuilder().addBuilder(
            DNSProtos.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public DNSProtos.Address.Builder addAddressBuilder(
          int index) {
        return getAddressFieldBuilder().addBuilder(
            index, DNSProtos.Address.getDefaultInstance());
      }
      /**
       * <code>repeated .Address address = 1;</code>
       */
      public java.util.List<DNSProtos.Address.Builder> 
           getAddressBuilderList() {
        return getAddressFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DNSProtos.Address, DNSProtos.Address.Builder, DNSProtos.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DNSProtos.Address, DNSProtos.Address.Builder, DNSProtos.AddressOrBuilder>(
                  address_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddressList)
    }

    // @@protoc_insertion_point(class_scope:AddressList)
    private static final DNSProtos.AddressList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DNSProtos.AddressList();
    }

    public static DNSProtos.AddressList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AddressList>
        PARSER = new com.google.protobuf.AbstractParser<AddressList>() {
      public AddressList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddressList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressList> getParserForType() {
      return PARSER;
    }

    public DNSProtos.AddressList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_KnownAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_KnownAddress_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddressList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DNSProto.proto\"|\n\007Address\022\016\n\006domain\030\001 " +
      "\002(\t\022\n\n\002ip\030\002 \002(\t\022+\n\014knownaddress\030\003 \003(\0132\025." +
      "Address.KnownAddress\032(\n\014KnownAddress\022\013\n\003" +
      "dmn\030\001 \001(\t\022\013\n\003ips\030\002 \001(\t\"(\n\013AddressList\022\031\n" +
      "\007address\030\001 \003(\0132\010.AddressB\013B\tDNSProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Domain", "Ip", "Knownaddress", });
    internal_static_Address_KnownAddress_descriptor =
      internal_static_Address_descriptor.getNestedTypes().get(0);
    internal_static_Address_KnownAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_KnownAddress_descriptor,
        new java.lang.String[] { "Dmn", "Ips", });
    internal_static_AddressList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddressList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddressList_descriptor,
        new java.lang.String[] { "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
